baseURL: "http://example.org/"
languageCode: "de"
title: "Lagerbuddy Website"
theme: "lagerbuddy"

params:
    logo: 'img/lb.png'
    logo_mono: 'img/lb-2.svg'
menus:
    header:
        - name: Service
          pageRef: /service
          weight: 1
        - name: Hilfe
          pageRef: /help
          weight: 2
        - name: Preise
          pageRef: /prices
          weight: 3
        - name: Kontakt
          pageRef: /contact
          weight: 4
    footer:
        - name: Allgemeine Info
          weight: 1
        - name: Rechtliches
          weight: 2
        - name: Mobile App
          weight: 3
        - name: AGB's
          parent: Rechtliches
          pageRef: /terms-of-use
          weight: 30
        - name: Datenschutzhinweise
          parent: Rechtliches
          pageRef: /data-protection
          weight: 20
        - name: Impressum
          parent: Rechtliches
          pageRef: /imprint
          weight: 20
        - name: OSS-Lizenzen
          parent: Mobile App
          pageRef: /imprint
          weight: 20
        - name: Drittsoftware und -dienste
          parent: Mobile App
          pageRef: /imprint
          weight: 10
        - name: Eula
          parent: Mobile App
          pageRef: /imprint
          weight: 30
        - name: Ãœber uns
          parent: Allgemeine Info
          pageRef: /terms-of-use
          weight: 10
        - name: Kontakt
          parent: Allgemeine Info
          pageRef: /imprint
          weight: 20
        - name: Blog
          parent: Allgemeine Info
          pageRef: /imprint
          weight: 30

# markup:
#   goldmark:
#     renderer:
#       hardWraps: true
#       unsafe: false

        
        
